# Movie Recommendation System

## Abstract
__The movie recommender system aims to provide personalized movie recommendations based on a given movie. By leveraging various features such as genre, keywords, cast, and crew, the system uses machine learning algorithms to find and suggest movies that are similar to the input movie, enhancing the user experience by helping them discover new content.__

## Problem Statement
__The primary objective of this project is to develop a recommendation engine that can accurately suggest top 5 movies similar to a given movie. The challenge lies in effectively combining different features and selecting an appropriate machine learning model to compute similarities between movies.__

![title](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp0lOO9waeTB4BUaNUfNeuOTEzaxRO7YHycQ&s,width=2100,height=2100)

## Dataset Description
The dataset for this project consists of movie information, including:

__movie_id__: Unique identifier for each movie.

__title__: Title of the movie.

__overview__: A brief description of the movie plot.

__genre__: The genre(s) of the movie.
    
__keywords__: Keywords describing the movie's themes and elements.

__cast__: List of main actors in the movie.

__crew__: List of main crew members (e.g., director).

# Importing Libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import ast
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

### Loads the credits dataset from a CSV file into a pandas DataFrame.
### Loads the movies dataset from a CSV file into a pandas DataFrame.

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# Data Cleaning and Data Preprocessing

In [6]:
movies = movies.merge(credits,on='title') # Merge movies and credits DataFrames on the 'title' column

In [7]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.isnull().sum()

budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
movie_id                0
cast                    0
crew                    0
dtype: int64

In [11]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']] # Select specific columns from the movies DataFrame

In [12]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]

In [14]:
import ast # Import the ast module for parsing strings into Python objects

In [15]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
def convert(text):                         # Convert the text to a list of dictionaries and extract names
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [17]:
movies['genres'] = movies['genres'].apply(convert)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def convert3(text):    # Extracts up to the first three 'name' values from a string representation of a list of dictionaries
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [21]:
movies['cast'] = movies['cast'].apply(convert3)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
 # Extracts and returns a list of names where the job is 'Director' from a string representation of a list of dictionaries

In [24]:
def fetch_director(text):               
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [25]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [27]:
# Removes all spaces from each string in the list L and returns the modified list

In [28]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [29]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [31]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [32]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [33]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

#### Concatenates the list of tags into a single space-separated string for each entry in the 'tags' column and displays the first few rows of the DataFrame

In [34]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [35]:
new['tags'] = new['tags'].apply(lambda x:x.lower())

In [36]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [37]:
new['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [38]:
new['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

# Vectorization 

#### Vectorization in machine learning refers to the process of converting textual data into numerical vectors so that machine learning algorithms can process them. This is a crucial step in natural language processing (NLP) tasks, where the input data is often in text form, which needs to be transformed into a format suitable for mathematical computations.

#### Initializes a CountVectorizer to convert text data into a matrix of token counts, limited to the top 5000 features and excluding common English stop words

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

#### Fits the CountVectorizer to the 'tags' column and transforms the text data into a matrix of token counts, then converts it to a dense array

In [40]:
vector = cv.fit_transform(new['tags']).toarray()

In [41]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
vector.shape

(1494, 5000)

In [43]:
cvs = cv.get_feature_names_out()
print(list(cvs))

['00', '000', '007', '10', '100', '11', '12', '14', '15', '16', '17', '18th', '1950s', '1960s', '1970s', '1979', '1980s', '1985', '1999', '19th', '19thcentury', '20', '2003', '2008', '2016', '2019', '20th', '21stcentury', '24', '25', '30', '300', '3d', '40', '50', '500', '60s', '70', 'aaron', 'aaroneckhart', 'abandoned', 'abbiecornish', 'abducted', 'abigailbreslin', 'ability', 'able', 'abuse', 'academy', 'accept', 'accepts', 'access', 'accident', 'accidentally', 'accompanied', 'account', 'accused', 'achieve', 'act', 'action', 'actions', 'activist', 'activities', 'activity', 'actor', 'actors', 'actually', 'adam', 'adamsandler', 'adamshankman', 'adaptation', 'addiction', 'adjust', 'admiration', 'adolescence', 'adopted', 'adoption', 'adorable', 'adrenaline', 'adrian', 'adrienbrody', 'adrift', 'adult', 'adultery', 'adults', 'advantage', 'adventure', 'adventures', 'advertising', 'advice', 'affair', 'affection', 'affections', 'afghanistan', 'africa', 'african', 'africanamerican', 'aftercreditsstinger', 'afterlife', 'aftermath', 'age', 'aged', 'agedifference', 'agency', 'agenda', 'agent', 'agents', 'aging', 'ago', 'agrees', 'ahead', 'aid', 'aided', 'aids', 'ailing', 'aims', 'air', 'airborne', 'airplane', 'airport', 'aka', 'al', 'alaska', 'albert', 'alcohol', 'alcoholic', 'alcoholism', 'aldous', 'alecbaldwin', 'alex', 'alexkendrick', 'ali', 'alice', 'alien', 'alieninvasion', 'alienplanet', 'aliens', 'alike', 'alive', 'alliance', 'allied', 'allies', 'allow', 'ally', 'alongside', 'alpacino', 'alpha', 'alter', 'alternate', 'alternatehistory', 'alternative', 'alvin', 'alzheimer', 'amandaseyfried', 'amazing', 'amazon', 'ambassador', 'amberheard', 'ambition', 'ambitious', 'ambush', 'america', 'american', 'americanabroad', 'americandream', 'americanfootball', 'americanfootballplayer', 'americans', 'amid', 'amnesia', 'amp', 'amsterdam', 'amusementpark', 'amyadams', 'anakin', 'analyst', 'anarchist', 'ancient', 'ancientgreece', 'ancientworld', 'anderson', 'andrewgarfield', 'andrewstanton', 'android', 'andy', 'andyserkis', 'angel', 'angeles', 'angelinajolie', 'angels', 'anger', 'anglee', 'angry', 'animal', 'animalattack', 'animalhorror', 'animallead', 'animals', 'animated', 'animation', 'anime', 'ann', 'anna', 'annabelle', 'annafaris', 'annakendrick', 'anne', 'annehathaway', 'annemoss', 'annettebening', 'annie', 'annual', 'anonymous', 'answer', 'answers', 'ant', 'antarctic', 'antarctica', 'anthony', 'anthonyhopkins', 'anthonymackie', 'anthonyrusso', 'anthropomorphism', 'anti', 'antics', 'antihero', 'antiterror', 'antoniobanderas', 'antonyelchin', 'anxious', 'apart', 'apartheid', 'apartment', 'apes', 'apocalypse', 'apocalyptic', 'appear', 'appearance', 'appears', 'appointed', 'apprentice', 'approaches', 'approaching', 'april', 'aquarium', 'arab', 'arbitrarylaw', 'arcade', 'arch', 'archaeologist', 'archenemy', 'archeology', 'archer', 'archery', 'architect', 'area', 'arena', 'argument', 'aristocrat', 'arizona', 'ark', 'armed', 'arms', 'armsdealer', 'army', 'arnoldschwarzenegger', 'arrangement', 'arrest', 'arrested', 'arrival', 'arrive', 'arrives', 'arriving', 'arrogant', 'arson', 'art', 'artgallery', 'arthur', 'article', 'artificial', 'artificialinsemination', 'artificialintelligence', 'artist', 'artistic', 'artists', 'arts', 'asabutterfield', 'asgard', 'ash', 'ashley', 'ashtonkutcher', 'asia', 'ask', 'asked', 'asks', 'asleep', 'asperger', 'aspiring', 'assassin', 'assassinate', 'assassination', 'assassins', 'assault', 'assigned', 'assignment', 'assist', 'assistant', 'assumes', 'astronaut', 'asylum', 'atheist', 'athlete', 'atlanticocean', 'atomicbomb', 'attack', 'attacked', 'attacks', 'attempt', 'attempts', 'attempttoescape', 'attending', 'attends', 'attention', 'attorney', 'attraction', 'attractive', 'audience', 'audiences', 'audition', 'audreytautou', 'august', 'aunt', 'australia', 'australian', 'author', 'authorities', 'authority', 'auto', 'autobots', 'automaton', 'automobileracing', 'avenge', 'avengers', 'average', 'avoid', 'awaits', 'awakens', 'award', 'away', 'awry', 'baby', 'babysitter', 'bachelor', 'backdrop', 'backed', 'backstage', 'backyard', 'bad', 'badly', 'bahamas', 'bail', 'balance', 'ball', 'ballet', 'baltasarkormákur', 'balthazar', 'band', 'bandit', 'bangkok', 'banished', 'bank', 'banker', 'banking', 'bankrobbery', 'bar', 'bargained', 'barn', 'barnes', 'barney', 'baron', 'barry', 'barrysonnenfeld', 'bars', 'base', 'baseball', 'based', 'basedonchildren', 'basedoncomicbook', 'basedonfairytale', 'basedongraphicnovel', 'basedonnovel', 'basedonplay', 'basedonstagemusical', 'basedontrueevents', 'basedontruestory', 'basedontvseries', 'basedonvideogame', 'basedonyoungadultnovel', 'basement', 'basketball', 'bathhouse', 'bathtub', 'batman', 'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach', 'bear', 'beard', 'bears', 'beast', 'beasts', 'beat', 'beating', 'beautiful', 'beautifulwoman', 'beauty', 'becca', 'becky', 'becominganadult', 'bed', 'bee', 'beer', 'befriends', 'began', 'begin', 'beginning', 'begins', 'behavior', 'beings', 'beliefs', 'believe', 'believed', 'believes', 'believing', 'bella', 'beloved', 'ben', 'benaffleck', 'bending', 'beneath', 'benfoster', 'beniciodeltoro', 'benjamin', 'benkingsley', 'bennet', 'bennett', 'benstiller', 'bent', 'benwhishaw', 'berlin', 'bertie', 'best', 'bestfriend', 'bestfriendsinlove', 'beth', 'bethany', 'betrayal', 'betrayed', 'better', 'beverly', 'bfg', 'bible', 'bid', 'big', 'biggest', 'bike', 'biker', 'bikini', 'bilbo', 'billhader', 'billionaire', 'billnighy', 'billpaxton', 'billpullman', 'billy', 'billybobthornton', 'billyburke', 'billyconnolly', 'bio', 'biography', 'bird', 'birth', 'birthday', 'bishop', 'bit', 'bite', 'biting', 'bitten', 'bittersweet', 'bizarre', 'black', 'blackandwhite', 'blackmagic', 'blackmail', 'blackpeople', 'blacksmith', 'blade', 'blakelively', 'blame', 'blart', 'blast', 'blind', 'blizzard', 'block', 'blofeld', 'blog', 'blood', 'bloodsplatter', 'bloodthirsty', 'bloody', 'blowing', 'blown', 'blu', 'blue', 'blunt', 'board', 'boardingschool', 'boat', 'boatchase', 'bob', 'bobby', 'bobbyfarrelly', 'body', 'bodyguard', 'bodyhorror', 'bold', 'bollywood', 'bolt', 'bomb', 'bombing', 'bond', 'bondage', 'boo', 'book', 'books', 'boomer', 'boov', 'booze', 'border', 'bored', 'borg', 'boring', 'born', 'boss', 'boston', 'bound', 'boundaries', 'bounty', 'bountyhunter', 'bourne', 'bowandarrow', 'bowling', 'box', 'boxer', 'boy', 'boyd', 'boyfriend', 'boyle', 'boys', 'bradbird', 'bradfurman', 'bradleycooper', 'bradpeyton', 'bradpitt', 'brain', 'brand', 'brandon', 'brave', 'bravery', 'brazilian', 'break', 'breaking', 'breakingthefourthwall', 'breaks', 'breakthrough', 'breast', 'breathing', 'brendan', 'brendanfraser', 'brendangleeson', 'brent', 'brian', 'briancox', 'brianrobbins', 'briantaylor', 'bride', 'bridesmaid', 'bridge', 'brielarson', 'brien', 'brilliant', 'bring', 'bringing', 'brings', 'brink', 'britain', 'british', 'britishsecretservice', 'britt', 'brock', 'broke', 'broken', 'brokenhearted', 'brooklyn', 'brooklynnewyorkcity', 'broom', 'brothel', 'brother', 'brotherbrotherrelationship', 'brothers', 'brothersisterrelationship', 'brought', 'brown', 'bruce', 'brucewillis', 'brutal', 'brutality', 'brutally', 'bryan', 'bryancranston', 'bryansinger', 'bryce', 'brycedallashoward', 'buddy', 'buddycomedy', 'budget', 'build', 'building', 'bullet', 'bully', 'bullying', 'bunker', 'bunny', 'burglar', 'buried', 'burke', 'burlesque', 'bush', 'business', 'businessman', 'businesswoman', 'busy', 'butcher', 'butler', 'button', 'buy', 'cabin', 'cage', 'cairo', 'cal', 'caleb', 'california', 'called', 'calls', 'calvin', 'cambridge', 'camcorder', 'came', 'camera', 'cameraman', 'cameras', 'camerondiaz', 'camgigandet', 'camp', 'campaign', 'campus', 'canada', 'canadian', 'cancer', 'candle', 'candlelightvigil', 'candy', 'canine', 'cannabis', 'canon', 'cao', 'capable', 'capitalism', 'captain', 'captive', 'capture', 'captured', 'car', 'caraccident', 'carchase', 'carcrash', 'card', 'cardgame', 'care', 'career', 'carefree', 'carefully', 'caretaker', 'carexplosion', 'careymulligan', 'caribbean', 'caring', 'carjourney', 'carl', 'carlagugino', 'carlossaldanha', 'carlton', 'carnival', 'carolina', 'carpet', 'carrace', 'carrie', 'carriefisher', 'carry', 'carrying', 'cars', 'carsetonfire', 'carter', 'cartoon', 'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castle', 'cat', 'cataclysm', 'catacombs', 'catandmouse', 'catastrophe', 'catch', 'catches', 'cateblanchett', 'catherinehardwicke', 'catherinekeener', 'catherinezeta', 'catholic', 'catholicism', 'caught', 'cause', 'caused', 'causes', 'causing', 'cavalry', 'cave', 'cavemen', 'celebrated', 'celebration', 'celebrity', 'cell', 'cello', 'cellphone', 'cemetery', 'center', 'centered', 'central', 'centuries', 'century', 'ceo', 'ceremony', 'certain', 'cesar', 'cgi', 'chadmichaelmurray', 'chain', 'challenge', 'challenged', 'challenges', 'challenging', 'champion', 'championship', 'chance', 'chaney', 'change', 'changed', 'changes', 'changing', 'changingthepastorfuture', 'channingtatum', 'chaos', 'chaotic', 'chappie', 'chapter', 'character', 'characters', 'charge', 'charged', 'charismatic', 'charles', 'charlesferguson', 'charlie', 'charlieday', 'charlizetheron', 'charm', 'charming', 'chase', 'chases', 'chasesandraces', 'cheating', 'checks', 'chef', 'chemical', 'chicago', 'chicken', 'chief', 'child', 'childabuse', 'childhero', 'childhood', 'childhoodmemory', 'childprodigy', 'children', 'chimp', 'chimps', 'china', 'chinese', 'chipettes', 'chipmunk', 'chipmunks', 'chiwetelejiofor', 'chloëgracemoretz', 'choice', 'choices', 'choose', 'chosen', 'chosenone', 'chris', 'chriscolumbus', 'chriscooper', 'chrisevans', 'chrishemsworth', 'chrispine', 'chrispratt', 'chrisrenaud', 'christ', 'christian', 'christianbale', 'christianity', 'christinaapplegate', 'christinaricci', 'christine', 'christmas', 'christmasparty', 'christopher', 'christopherlloyd', 'christophermiller', 'christophernolan', 'christopherplummer', 'christopherwalken', 'christophwaltz', 'chrisweitz', 'chronicle', 'chronicles', 'chu', 'church', 'churchservice', 'cia', 'ciaagent', 'ciaránhinds', 'cigarettesmoking', 'cillianmurphy', 'cinderella', 'cindy', 'cinema', 'circumstances', 'circus', 'cities', 'citizens', 'city', 'civil', 'civilization', 'claim', 'claims', 'claire', 'clan', 'clary', 'class', 'classdifferences', 'classic', 'classicalmusic', 'classmate', 'classroom', 'clean', 'clerk', 'client', 'climate', 'climatechange', 'climbing', 'clinteastwood', 'clique', 'cliveowen', 'clock', 'clocks', 'clone', 'cloning', 'clooney', 'close', 'closed', 'closer', 'closing', 'club', 'clubs', 'clue', 'clueless', 'clues', 'clutches', 'coach', 'coast', 'cocaine', 'cockburn', 'code', 'codes', 'coffin', 'cohen', 'cold', 'coldwar', 'colinfarrell', 'collapse', 'collector', 'college', 'collide', 'collins', 'collision', 'colombia', 'colony', 'coma', 'combat', 'combination', 'come', 'comeback', 'comedian', 'comedy', 'comes', 'comfort', 'comic', 'coming', 'comingofage', 'comingout', 'commander', 'commitment', 'committed', 'common', 'community', 'companions', 'company', 'compete', 'competition', 'complete', 'completely', 'complex', 'complicated', 'complications', 'compound', 'computer', 'concert', 'condition', 'confident', 'conflict', 'confront', 'confronted', 'conman', 'connection', 'connell', 'connor', 'conquer', 'consequences', 'considered', 'conspiracy', 'conspiracyofmurder', 'constantly', 'contact', 'contain', 'containing', 'contend', 'contender', 'contest', 'continent', 'continue', 'continues', 'contract', 'contracts', 'control', 'controlled', 'controlling', 'controversial', 'converge', 'convict', 'convince', 'convinces', 'cook', 'cooking', 'cop', 'cope', 'cops', 'core', 'corleone', 'corner', 'corporate', 'corporation', 'corpse', 'corrupt', 'corruption', 'cost', 'costasmandylor', 'costume', 'count', 'countdown', 'counter', 'countless', 'countries', 'country', 'countryhouse', 'countryside', 'county', 'coup', 'coupd', 'couple', 'couples', 'courage', 'courageous', 'course', 'court', 'cousin', 'coven', 'cover', 'covert', 'cowardliness', 'cowboy', 'cox', 'crack', 'craig', 'craiggillespie', 'crash', 'crazy', 'create', 'created', 'creates', 'creature', 'creatures', 'crew', 'crime', 'crimefighter', 'crimes', 'criminal', 'criminals', 'crisis', 'cross', 'crossed', 'crosses', 'cruel', 'cruelty', 'cruise', 'crush', 'crying', 'cullen', 'cult', 'cultfilm', 'culture', 'cultureclash', 'cup', 'cure', 'current', 'curse', 'custody', 'cut', 'cyberpunk', 'cyborg', 'dad', 'daily', 'damage', 'dan', 'dance', 'dancer', 'dancing', 'danger', 'dangerous', 'danielcraig', 'danielradcliffe', 'danny', 'dannyboyle', 'dannymcbride', 'dare', 'daring', 'dark', 'darkcomedy', 'darker', 'darkest', 'darkfantasy', 'darkness', 'darkpast', 'darrenaronofsky', 'darryl', 'darth', 'dashing', 'date', 'dating', 'daughter', 'daughters', 'dave', 'david', 'davidbowers', 'davidcronenberg', 'davidcross', 'davidfincher', 'davidgordongreen', 'davidhand', 'dawn', 'day', 'days', 'dc', 'dccomics', 'dead', 'deadly', 'deal', 'dealer', 'dealers', 'dealing', 'dean', 'death', 'deathofafriend', 'deathstar', 'debt', 'decade', 'deceit', 'decepticons', 'deception', 'decide', 'decided', 'decides', 'decision', 'decisions', 'deep', 'deeply', 'defeat', 'defeating', 'defend', 'defense', 'defies', 'deliver', 'delivers', 'delivery', 'delorean', 'delusion', 'demands', 'democracy', 'demon', 'demonic', 'demonicpossession', 'demons', 'denis', 'denisleary', 'dennisdugan', 'dennisquaid', 'denny', 'dent', 'dentist', 'denzelwashington', 'department', 'deportation', 'depressed', 'depression', 'derek', 'dermotmulroney', 'descend', 'descends', 'deschanel', 'desert', 'deserted', 'design', 'designed', 'desire', 'despair', 'desperate', 'desperately', 'despite', 'destination', 'destined', 'destiny', 'destroy', 'destroyed', 'destroyer', 'destroying', 'destruction', 'details', 'detective', 'detectives', 'detention', 'determination', 'determine', 'determined', 'detroit', 'develop', 'developed', 'developing', 'develops', 'device', 'devil', 'devoted', 'dewey', 'diabolical', 'dialogue', 'diamond', 'diane', 'dianekeaton', 'dianekruger', 'dianelane', 'diary', 'dick', 'dictator', 'did', 'didn', 'die', 'diego', 'dies', 'differences', 'different', 'difficult', 'dilemma', 'dillinger', 'diner', 'dinner', 'dinosaur', 'dinosaurs', 'dire', 'directed', 'direction', 'director', 'directs', 'dirty', 'dirtycop', 'disappearance', 'disappeared', 'disappears', 'disaster', 'discover', 'discovered', 'discovering', 'discovers', 'discovery', 'disease', 'disgraced', 'disguise', 'dishonesty', 'disillusioned', 'disorder', 'dispatched', 'distance', 'distant', 'district', 'distrust', 'disturbed', 'disturbing', 'ditch', 'divergent', 'divided', 'divorce', 'divorced', 'dna', 'doc', 'doctor', 'document', 'documentary', 'documents', 'does', 'doesn', 'dog', 'dogs', 'doing', 'doll', 'dollar', 'dolphin', 'dolphlundgren', 'domesticated', 'domhnallgleeson', 'dominance', 'domination', 'dominatrix', 'dominicwest', 'don', 'donaldsutherland', 'doncheadle', 'donkey', 'donnell', 'doomed', 'doomsday', 'door', 'doorstep', 'dormant', 'dorothy', 'double', 'doublelife', 'doubt', 'doug', 'dougliman', 'downsizing', 'dr', 'dracula', 'dragged', 'dragon', 'drama', 'dramatic', 'draw', 'drawing', 'drawn', 'draws', 'dream', 'dreams', 'drewbarrymore', 'drifter', 'drink', 'drinking', 'drive', 'driven', 'driver', 'drop', 'dropped', 'drug', 'drugaddiction', 'drugdealer', 'druglord', 'drugs', 'drugsmuggle', 'drugtraffic', 'druguse', 'drummer', 'drunk', 'drunken', 'du', 'dualidentity', 'dubbed', 'dublin', 'dude', 'duel', 'duke', 'dumps', 'duncanjones', 'duo', 'duringcreditsstinger', 'dustinhoffman', 'duty', 'dwarves', 'dwaynejohnson', 'dying', 'dyinganddeath', 'dylan', 'dynasty', 'dysfunctional', 'dysfunctionalfamily', 'dystopia', 'dystopicfuture', 'eager', 'earlier', 'early', 'earn', 'earned', 'earth', 'earthquake', 'east', 'eastern', 'eastindiatradingcompany', 'easy', 'eating', 'eccentric', 'economic', 'economics', 'economy', 'ed', 'eddie', 'eddiemurphy', 'edge', 'edharris', 'edhelms', 'editor', 'education', 'edward', 'edwardnorton', 'edwards', 'effort', 'efforts', 'egg', 'ego', 'egypt', 'egyptian', 'elaborate', 'elderly', 'elected', 'elegant', 'elements', 'elevator', 'eliaskoteas', 'elijahwood', 'eliminate', 'elite', 'elizabeth', 'elizabethbanks', 'ella', 'ellefanning', 'ellenburstyn', 'ellenpage', 'elliot', 'elliott', 'ellis', 'elsa', 'elusive', 'elves', 'embark', 'embarking', 'embarks', 'ember', 'embroiled', 'emerald', 'emerge', 'emergency', 'emerges', 'emilehirsch', 'emily', 'emilyblunt', 'emilybrowning', 'emilywatson', 'emma', 'emmaroberts', 'emmastone', 'emmawatson', 'emotional', 'emotionally', 'emotions', 'emperor', 'empire', 'employee', 'employer', 'employs', 'enchantment', 'encounter', 'encounters', 'end', 'ended', 'ending', 'endoftheworld', 'ends', 'enemies', 'enemy', 'energy', 'enforcement', 'engaged', 'engagement', 'engaging', 'engineer', 'engineered', 'england', 'english', 'enigmatic', 'enlist', 'enlists', 'enormous', 'ensemblecast', 'ensues', 'entei', 'enter', 'enters', 'entire', 'entirely', 'entity', 'entrepreneur', 'environment', 'environmental', 'envisions', 'epic', 'epidemic', 'episode', 'equal', 'era', 'eric', 'ericbana', 'erin', 'eroticism', 'escapade', 'escape', 'escaped', 'escapefromprison', 'escapes', 'escaping', 'escort', 'especially', 'espionage', 'established', 'estate', 'esther', 'estranged', 'etat', 'eternal', 'ethan', 'ethanhawke', 'europe', 'evacuation', 'evagreen', 'evalongoria', 'evamendes', 'evanrachelwood', 'eve', 'evening', 'event', 'events', 'eventually', 'everybody', 'everyday', 'evidence', 'evil', 'evilcorporation', 'evilwitch', 'evolution', 'evolving', 'ewanmcgregor', 'ex', 'exact', 'exactly', 'exam', 'examines', 'exchange', 'exciting', 'excuses', 'execution', 'executive', 'exercise', 'exist', 'existed', 'existence', 'existentialism', 'exists', 'exorcism', 'exotic', 'exoticisland', 'expectations', 'expected', 'expedition', 'expendables', 'experience', 'experienced', 'experiences', 'experiment', 'expert', 'expertise', 'experts', 'explain', 'explodes', 'explodingbuilding', 'explorers', 'explores', 'explosion', 'explosive', 'expose', 'exposed', 'exposes', 'extinction', 'extra', 'extramaritalaffair', 'extraordinary', 'extraterrestrialtechnology', 'extravagant', 'extreme', 'extremeviolence', 'eye', 'eyes', 'fabled', 'face', 'faced', 'faces', 'facility', 'facing', 'fact', 'factions', 'factory', 'fade', 'fail', 'failed', 'failing', 'fails', 'fairy', 'fairytale', 'faith', 'fake', 'falcon', 'fall', 'fallen', 'falling', 'fallinginlove', 'falls', 'falseidentity', 'falsely', 'falselyaccused', 'fame', 'famed', 'families', 'family', 'familyrelationships', 'famous', 'fangvamp', 'fans', 'fantastic', 'fantasy', 'fantasyworld', 'far', 'farewell', 'farm', 'farmer', 'farmers', 'farmhouse', 'fascism', 'fascist', 'fashion', 'fast', 'faster', 'fat', 'fatal', 'fate', 'fated', 'fateful', 'father', 'fatherdaughterrelationship', 'fathers', 'fathersonrelationship', 'favorite', 'fbi', 'fbiagent', 'fear', 'feared', 'fears', 'fearsome', 'feature', 'features', 'featuring', 'feel', 'feeling', 'feelings', 'feels', 'feet', 'feisty', 'felix', 'fellow', 'fellowship', 'female', 'femalecorpse', 'femalefriendship', 'femalenudity', 'femaleprotagonist', 'females', 'femalevampire', 'femmefatale', 'fergus', 'ferris', 'festival', 'feud', 'fi', 'fiancee', 'fiancé', 'fiction', 'fictional', 'fictionalgovernmentagency', 'fido', 'field', 'fierce', 'fifth', 'fight', 'fighter', 'fighting', 'fights', 'figure', 'filled', 'film', 'filmed', 'filming', 'filmmaker', 'filmmakers', 'filmmaking', 'filmproducer', 'films', 'final', 'finally', 'financial', 'financialcrisis', 'finding', 'finds', 'fine', 'fingerprints', 'finish', 'finn', 'fiona', 'firearm', 'fired', 'firemen', 'fireworks', 'firm', 'firstlove', 'firsttime', 'fish', 'fisherman', 'fishing', 'fishoutofwater', 'fistfight', 'fit', 'fitting', 'fitz', 'fitzgerald', 'fix', 'fixer', 'flame', 'flashback', 'flat', 'fledgling', 'flees', 'flesh', 'flight', 

In [44]:
import nltk

In [45]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [46]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [47]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.'

In [48]:
new['tags']=new['tags'].apply(stem)

#### Imports the cosine_similarity function to compute the similarity between vectors based on cosine distance

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity = cosine_similarity(vector)

In [51]:
similarity

array([[1.        , 0.08134892, 0.05423261, ..., 0.        , 0.05504819,
        0.02469324],
       [0.08134892, 1.        , 0.05882353, ..., 0.04428074, 0.        ,
        0.        ],
       [0.05423261, 0.05882353, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.04428074, 0.        , ..., 1.        , 0.        ,
        0.04032389],
       [0.05504819, 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.02469324, 0.        , 0.        , ..., 0.04032389, 0.        ,
        1.        ]])

In [52]:
new[new['title'] == 'The Lego Movie'].index[0]

744

In [53]:
def recommend(movie):      # Find the index of the input movie title in the DataFrame
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [54]:
recommend('Avatar')

Aliens vs Predator: Requiem
Battle: Los Angeles
Ender's Game
Apollo 18
Edge of Tomorrow

In [55]:
import pickle

In [56]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))